2/3 api_demod tests working, 3rd one is close, notes in tst_api_demod_check

diff --git a/stm32/unittest/scripts/run_stm32_tst b/stm32/unittest/scripts/run_stm32_tst
--- a/stm32/unittest/scripts/run_stm32_tst
+++ b/stm32/unittest/scripts/run_stm32_tst
@@ -28,7 +28,11 @@ fi
 ${TEST}_setup ${TEST} ${TEST_OPT} --clean || { echo "ERROR in ${TEST}_setup! Exiting..."; exit 1; }
 cd "${RUN_DIR}" 
 run_stm32_prog ${UNITTEST_BIN}/${TEST}.elf ${LOAD} ${OPENOCD} |& tee gdb.log
-${TEST}_check ${TEST} ${TEST_OPT} 2>&1 | tee check.log || let Fails=($Fails + 1)
+${TEST}_check ${TEST} ${TEST_OPT} 2>&1 | tee check.log
+# fancy bash way of testing fail code of first command in pipe
+if [ ! "${PIPESTATUS[0]}" -eq 0 ]; then
+    let Fails=($Fails + 1)
+fi
 
 sleep 5 # Delay for st-util to close
 
@@ -37,7 +41,7 @@ if (( $Fails == 0 )); then
 else
     echo -e "\nTest ${FULL_TEST_NAME} FAILED!"
     cat ${RUN_DIR}/check.log
-    echo -e "\n  -> look in: ${RUN_DIR} ......"
+    echo -e "\n  -> look at log files in: ${RUN_DIR} "
 fi
 
 exit $Fails
